package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/toshim45/demo-gqlgen/graph/model"
	"github.com/toshim45/demo-gqlgen/graph/query"
)

// Thing is the resolver for the thing field.
func (r *queryResolver) Thing(ctx context.Context, limit *int, offset *int, where *model.ThingsBoolExp) ([]*model.Thing, error) {
	return query.ResolveThing(limit, offset, where)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
